###
GET http://localhost:3067/

###

GET http://localhost:3067/steam

### 

### 

POST http://localhost:3067/steam
Content-Type: application/json

{
    "nome": "ori and the call of the wisps",
    "preco": "12,50",
    "nota": "5"
}

###
GET http://localhost:3067/serie

###

POST http://localhost:3067/serie
Content-Type: application/json

{
    "nome": "abc",
    "avaliacao": "5"
}

